export const productTypes = {
    SET_PAGE: 'SET_PAGE',
    SET_PRODUCT: 'SET_PRODUCT',
    SET_ALL_COLOR: 'SET_ALL_COLOR',
    SET_ALL_SIZE: 'SET_ALL_SIZE',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_CATEGORY_PRODUCT: 'SET_CATEGORY_PRODUCT',
    SET_ALL_CATEGORY_PRODUCT: 'SET_ALL_CATEGORY_PRODUCT',
    SET_BRAND: 'SET_BRAND',
    SET_PROMOTION_CODE: 'SET_PROMOTION_CODE',
    SET_BANNER: 'SET_BANNER',
    SET_ALL_BRAND: 'SET_ALL_BRAND',
    SET_COLOR: 'SET_COLOR',
    SET_SIZE: 'SET_SIZE',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL: 'ADD_CATEGORY_FAIL',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAIL: 'UPDATE_CATEGORY_FAIL',
    RESET_CATEGORY: 'RESET_CATEGORY',
    ADD_PROMOTION_CODE_SUCCESS: 'ADD_PROMOTION_CODE_SUCCESS',
    ADD_PROMOTION_CODE_FAIL: 'ADD_PROMOTION_CODE_FAIL',
    UPDATE_PROMOTION_CODE_SUCCESS: 'UPDATE_PROMOTION_CODE_SUCCESS',
    UPDATE_PROMOTION_CODE_FAIL: 'UPDATE_PROMOTION_CODE_FAIL',
    RESET_PROMOTION_CODE: 'RESET_PROMOTION_CODE',
    ADD_BANNER_SUCCESS: 'ADD_BANNER_SUCCESS',
    ADD_BANNER_FAIL: 'ADD_BANNER_FAIL',
    UPDATE_BANNER_SUCCESS: 'UPDATE_BANNER_SUCCESS',
    UPDATE_BANNER_FAIL: 'UPDATE_BANNER_FAIL',
    RESET_BANNER: 'RESET_BANNER',
    ADD_BRAND_SUCCESS: 'ADD_BRAND_SUCCESS',
    ADD_BRAND_FAIL: 'ADD_BRAND_FAIL',
    UPDATE_BRAND_SUCCESS: 'UPDATE_BRAND_SUCCESS',
    UPDATE_BRAND_FAIL: 'UPDATE_BRAND_FAIL',
    RESET_BRAND: 'RESET_BRAND',
    ADD_COLOR_SUCCESS: 'ADD_COLOR_SUCCESS',
    ADD_COLOR_FAIL: 'ADD_COLOR_FAIL',
    UPDATE_COLOR_SUCCESS: 'UPDATE_COLOR_SUCCESS',
    UPDATE_COLOR_FAIL: 'UPDATE_COLOR_FAIL',
    RESET_COLOR: 'RESET_COLOR',
    ADD_SIZE_SUCCESS: 'ADD_SIZE_SUCCESS',
    ADD_SIZE_FAIL: 'ADD_SIZE_FAIL',
    UPDATE_SIZE_SUCCESS: 'UPDATE_SIZE_SUCCESS',
    UPDATE_SIZE_FAIL: 'UPDATE_SIZE_FAIL',
    RESET_SIZE: 'RESET_SIZE',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAIL: 'UPDATE_PRODUCT_FAIL',
    RESET_PRODUCT: 'RESET_PRODUCT',
    BRAND_SET_PAGE: 'BRAND_SET_PAGE',
    BRAND_SET_TOTAL_PAGE: 'BRAND_SET_TOTAL_PAGE',
    COLOR_SET_PAGE: 'COLOR_SET_PAGE',
    COLOR_SET_TOTAL_PAGE: 'COLOR_SET_TOTAL_PAGE',
    SIZE_SET_PAGE: 'SIZE_SET_PAGE',
    SIZE_SET_TOTAL_PAGE: 'SIZE_SET_TOTAL_PAGE',
    CATEGORY_SET_PAGE: 'CATEGORY_SET_PAGE',
    CATEGORY_SET_TOTAL_PAGE: 'CATEGORY_SET_TOTAL_PAGE',
    ORDER_SET_PAGE: 'ORDER_SET_PAGE',
    ORDER_SET_TOTAL_PAGE: 'ORDER_SET_TOTAL_PAGE',
    ORDER_SET_DATA: "ORDER_SET_DATA",
    ORDER_SET_DATA_BY_ID:"ORDER_SET_DATA_BY_ID"

}

export const userTypes = {
    SET_USER: 'SET_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    RESET_USER: 'RESET_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE:'SET_TOTAL_PAGE'
}

export const homeTypes = {
    SET_TOP_PRODUCT:' SET_TOP_PRODUCT'
}
export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",
  
    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};
export const VIEW_HISTORY_REQUEST='VIEW_HISTORY_REQUEST';
export const VIEW_HISTORY_SUCCESS='VIEW_HISTORY_SUCCESS';
export const VIEW_HISTORY_FAIL='VIEW_HISTORY_FAIL';

export const REMOVE_ORDER_REQUEST='REMOVE_ORDER_REQUEST';
export const REMOVE_ORDER_SUCCESS='REMOVE_ORDER_SUCCESS';
export const REMOVE_ORDER_FAIL='REMOVE_ORDER_FAIL';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const GET_ORDER_BY_YEAR_REQUEST = 'GET_ORDER_BY_YEAR_REQUEST'
export const GET_ORDER_BY_YEAR_SUCCESS = 'GET_ORDER_BY_YEAR_SUCCESS'
export const GET_ORDER_BY_YEAR_FAIL = 'GET_ORDER_BY_YEAR_FAIL'

export const GET_SUB_TOTAL_BY_YEAR_REQUEST='GET_SUB_TOTAL_BY_YEAR_REQUEST'
export const GET_SUB_TOTAL_BY_YEAR_SUCCESS='GET_SUB_TOTAL_BY_YEAR_SUCCESS'
export const GET_SUB_TOTAL_BY_YEAR_FAIL='GET_SUB_TOTAL_BY_YEAR_FAIL'

export const GET_ORDER_SUBTOTAL_BY_CATEGORY_YEAR_REQUEST='GET_ORDER_SUBTOTAL_BY_CATEGORY_YEAR_REQUEST'
export const GET_ORDER_SUBTOTAL_BY_CATEGORY_YEAR_SUCCESS='GET_ORDER_SUBTOTAL_BY_CATEGORY_YEAR_SUCCESS'
export const GET_ORDER_SUBTOTAL_BY_CATEGORY_YEAR_FAIL='GET_ORDER_SUBTOTAL_BY_CATEGORY_YEAR_FAIL'

export const GET_QUANTITY_ORDER_BY_YEAR_REQUEST = 'GET_QUANTITY_ORDER_BY_YEAR_REQUEST'
export const GET_QUANTITY_ORDER_BY_YEAR_SUCCESS = 'GET_QUANTITY_ORDER_BY_YEAR_SUCCESS'
export const GET_QUANTITY_ORDER_BY_YEAR_FAIL = 'GET_QUANTITY_ORDER_BY_YEAR_FAIL'

export const GET_QUANTITY_ORDER_BY_CATEGORY_YEAR_REQUEST = 'GET_QUANTITY_ORDER_BY_YEAR_REQUEST'
export const GET_QUANTITY_ORDER_BY_CATEGORY_YEAR_SUCCESS = 'GET_QUANTITY_ORDER_BY_CATEGORY_YEAR_SUCCESS'
export const GET_QUANTITY_ORDER_BY_CATEGORY_YEAR_FAIL = 'GET_QUANTITY_ORDER_BY_CATEGORY_YEAR_FAIL'

export const GET_ORDER_BY_CATEGORY_YEAR_REQUEST = 'GET_ORDER_BY_YEAR_REQUEST'
export const GET_ORDER_BY_CATEGORY_YEAR_SUCCESS = 'GET_ORDER_BY_CATEGORY_YEAR_SUCCESS'
export const GET_ORDER_BY_CATEGORY_YEAR_FAIL = 'GET_ORDER_BY_CATEGORY_YEAR_FAIL'

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const UPDATE_PRICE_BY_CATEGORY_REQUEST = 'UPDATE_PRICE_BY_CATEGORY_REQUEST'
export const UPDATE_PRICE_BY_CATEGORY_SUCCESS = 'UPDATE_PRICE_BY_CATEGORY_SUCCESS'
export const UPDATE_PRICE_BY_CATEGORY_FAIL = 'UPDATE_PRICE_BY_CATEGORY_FAIL'